config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stocks#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :stocks, only: [:index,:new,:show,:create,:edit,:update,:destroy]
   get 'groups' => "groups#index"
   post '/stocks/:id/edit' => "stocks#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do  
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json'}
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  # mount_uploader :image, ImageUploader

  private
  def message_params
    params.require(:message).permit(:content).merge(group_id: current_group.id)
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_main.html.haml
.main-chat
  .member-list
    .left-list
      = @group.name 
      .left-list__members
        Member: 
        %ul
        - @group.users.each do |user|
          %li= user.name
    .right-list
      =link_to "Edit", edit_group_path(@group),class: "editlink"

  .messages
    = render @messages
 
  .form
    = form_for [@group, @message] do |f|
      = f.text_field :content, class: 'form__comment', placeholder: 'type a message'
      .form__space
        = f.label :image, class: 'form__space__image' do
          = icon('fa','image', class: 'img')
          = f.file_field :image, class: 'hide'
      = f.submit 'Send', class: 'form__submit'

app/views/messages/_main_chat.html.haml
.main-chat
  .member-list
    .left-list
      = @group.users 
      .left-list__members
        Member: 
        %ul
        - @group.users.each do |user|
          %li= user.user
    .right-list
      =link_to "Edit", edit_user_path(current_user),class: "editlink"

  .messages
    = render @message
 
  .form
    = form_with [@group, @message] do |f|
      = f.text_field :content, class: 'form__comment', placeholder: 'type a message'
      .form__space
        = f.label :image, class: 'form__space__image' do
          = icon('fa','image', class: 'img')
          = f.file_field :image, class: 'hide'
      = f.submit 'Send', class: 'form__submit'

app/views/messages/_message.html.haml
.message{data: {message: {id: message.id}}}
  .over
    .over__user-name
      = @message.user
    .over__date
      = @message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .under
    - if message.content.present?
      %p.under__content
        = message.content
    = image_tag message.image.url, class: 'under__comment__image' if message.image.present?

app/views/messages/_side-bar.html.haml
.side-bar
  .user-name
    .top-items
      .top-items__name
        = current_user.name
      %ul.top-items__function
        = link_to new_group_path do
          = icon('fa', 'edit',class: 'mark')
        = link_to edit_user_path(current_user) do
          = icon('fa', 'cog',class: 'mark')
  .group-list
    - current_user.groups.each do |group|
      .groups
        = link_to group_messages_path(group) do
          .groups__name
            = group.name
          .groups__message
            = group.show_last_message
    

app/views/messages/_side_bar.html.haml
.side-bar
  .user-name
    .top-items
      .top-items__name
        = current_user.name
      %ul.top-items__function
        = link_to new_group_path do
          = icon('fa', 'edit',class: 'mark')
        = link_to edit_user_path(current_user) do
          = icon('fa', 'cog',class: 'mark')
  .group-list
    - current_user.groups.each do |group|
      .groups
        = link_to group_messages_path(group) do
          .groups__name
            = group.name
          .groups__message
            = group.show_last_message
    

app/views/messages/index.html.haml
.message-page
  = render "side_bar"
  = render "main_chat"