config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stocks#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :stocks, only: [:index,:new,:show,:create,:edit,:update,:destroy]
   get 'groups' => "groups#index"
   post '/stocks/:id/edit' => "stocks#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do  
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json'}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :messages
  has_many :users, through: :group_users 
  validates :name, presence: true, uniqueness: true 

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  # mount_uploader :image, ImageUploader

  private
  def message_params
    params.require(:message).permit(:content).merge(group_id: current_group.id)
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :users, optional: true

  validates :name, :count, presence: true
  validates :name, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_users
  has_many :stocks
  has_many :groups, through: :group_users

  def self.search(input, id)
    return nil if input == ""
    User.where(['name LIKE ?', "%#{input}%"]).where.not(id: id).limit(10)
  end
    
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:store, :name, :email])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @group = Group.new
    @message = Message.new
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params) 
      redirect_to group_messages_path(@group)
    else
      render :edit
    end
  end 

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :login_required

  def index
    @users = User.all
    @stocks =Stock.all
  end
  
  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    if @stock.save
      redirect_to root_path
      return
    else
      flash.now[:alert] = '追加できませんでした'
      render :new
    end
  end

  def show
    stocks = stock_url(params[:id])
    @stocks = Stock.all
  end


  def edit
    @stocks = Stock.find(params[:id])
  end

  def update
    @stocks = Stock.find(params[:id])
    @stocks.update(update_params)
    redirect_to root_path
  end 

  def destroy
    @stock = Stock.find(params[:id])
    if @stock.destroy
      redirect_to root_path
    end
  end
  private

  def login_required 
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to new_user_session_path
    end
  end

  def update_params
    params.permit(:count)
  end

  def stock_params
    params.require(:stock).permit(:name,:count)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def index
    @users = User.search(params[:keyword], current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def user_params
    params.require(:user).permit(:store, :name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    %h2= "#{group.errors.full_messages.count}件のエラーが発生しました"
    %ul
      - group.errors.full_messages.each do |message|
        %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result
  
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
      
      -# = f.collection_check_boxes :user_ids, User.all, :id, :name
      
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chot-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'
  = render 'messages/main_chat'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group}

app/views/stocks/_add.html.haml
.primal
  .primal__top
    STOCK-APP 商品追加
    
  .add
    .add__area
      追加する商品名を入力してください
    .add-form__text
      = form_with model: @stock do |f|
        .add-form__text__stock__item
          = f.text_field :name, placeholder: "商品名を入力" 
          = f.number_field :count, placeholder: "在庫数を入力" 
          = f.submit '以上の商品を追加', class: 'form-decide__btn'

        #input_plurarBox
          #input_plural
            %input.form-control{ :type => "text" :placeholder =>"更に商品を追加する"}
            %input.add-pluralBtn{:type => "button" :value => "＋"}
            %input.del-pluralBtn{:type => "button" :value => "－"}
    .back
      = link_to "戻る", root_path,class: "back__btn"

app/views/stocks/_cal-item.html.haml
.primal
  .primal__top
    STOCK-APP 入荷・出荷

  .add
    .add__area
      =@stocks.name
      .add__area__text
        の在庫数を更新
  
    %table
      %tbody
        %tr
          %th.stock
            現在の在庫数
          %th.shipment
            在庫数の更新

        %tr
          %td
            =@stocks.count
          %td
            =form_with model: @stock,url: stock_path,method: :put do |f|
              =f.number_field :count , placeholder: "新規の在庫数"
              =f.submit "更新する"
                


      

app/views/stocks/_cancel.html.haml
.primal
  .primal__top
    STOCK-APP 商品取消

  .items-table
    .items-table__head
      商品一覧
    %table
      %tbody
        %tr
          %th.name
            商品名
          %th.stock
            在庫数
          %th.del
            取消

      - @stocks.each do |stock|
        %tr
          %td
            =stock.name
          %td
            =stock.count
          %td
            =link_to "取消",stock_path(stock.id), method: :delete, data: { confirm: '削除してよろしいですか?' }
      
    .back
      = link_to "戻る", root_path,class: "back__btn"

app/views/stocks/_items.html.haml
.primal
  .primal__top
    STOCK-APP 入荷・出荷

  .items-table
    .items-table__head
      商品一覧
    %table
      %tbody
        %tr
          %th.name
            商品名
          %th.stock
            在庫数
          %th.inc-dec
            在庫数の変更
      - @stocks.each do |stock|
        %tr.items-data
          %td
            =stock.name
          %td#stock-origin
            =stock.count
          %td
            =link_to "更新",edit_stock_path(stock.id)

app/views/stocks/_links.html.haml
.top-side
  .side-menu
    %ul.side-menu__names
      %li.side-menu__names__user
        =current_user.store
      %li.side-menu__names__user
        =current_user.name

  .menu
    .menu__top
      メニュー
      %ul.menu__top__lists
        %li.menu__top__lists__links
          = link_to "入荷・出荷",root_path,class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          = link_to "商品追加",new_stock_path,class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          = link_to "商品取消",stock_path(:id),class: "menu__top__lists__links__btn"
        %li.menu__top__lists__links
          =link_to "ログアウト", users_sign_out_path,class: "menu__top__lists__links__btn",id: "logout"
  

app/views/stocks/_stock.html.haml
.primal
  .primal__top
    在庫の取消・増減

  .items-table
    .items-table__head
      商品一覧
    %table
      %tbody
        %tr
          %th.name
            商品名
          %th.stock
            在庫数
          %th.del
            取消
          %th.inc-dec
            増減
      - @stocks.each do |stock|
        %tr
          %td
            =stock.item
          %td
            =stock.stock
          %td
            = link_to icon('fa','trash'),stock_path(stock.id), method: :delete, data: { confirm: '削除してよろしいですか?' }
          %td

app/views/stocks/create.html.erb
<h2>お疲れちゃん</h2>
<%= link_to 'トップページに戻る' '/stocks'%>

app/views/stocks/destroy .html.haml
.container
  = render "links"
  = render "del"

 





  

app/views/stocks/destroy.html.haml
.container
  = render "links"
  = render "del"

 





  

app/views/stocks/edit.html.haml
.container
  = render "links"
  = render "cal-item"

app/views/stocks/index.html.haml
.container
  = render "links"
  = render "items"

app/views/stocks/new.html.haml
%header.add
  .items__new
    .items__new__title
      新しい商品の追加

.input-name
  = form_with url: "#" do |form|
    = form.text_field :key, placeholder: "商品名を入力",class: "input-name__form"
    .input-name__form__btn
      フォームの追加
    #add.input-name__form__btn
      以上の商品を追加

%footer
  =render "totop"

      

    

app/views/stocks/show.html.haml
.container
  = render "links"
  = render "cancel"

app/views/stocks/update.html.haml
.container
  = render "links"
  = render "stock"